CREATE TABLE "focustimer_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "focustimer_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "focustimer_achievement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_achievement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" text NOT NULL,
	"icon" varchar(50),
	"badgeColor" varchar(20) DEFAULT '#10B981',
	"requirement" integer NOT NULL,
	"type" varchar(50) NOT NULL,
	"xpReward" integer DEFAULT 0,
	"isActive" boolean DEFAULT true,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "focustimer_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"color" varchar(20) DEFAULT '#3B82F6',
	"icon" varchar(50),
	"isDefault" boolean DEFAULT false,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "focustimer_focus_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_focus_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"categoryId" integer,
	"title" varchar(200),
	"plannedDuration" integer NOT NULL,
	"actualDuration" integer,
	"startedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completedAt" timestamp with time zone,
	"status" varchar(20) DEFAULT 'active',
	"isCompleted" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "focustimer_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "focustimer_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "focustimer_todo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_todo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"categoryId" integer,
	"title" varchar(200) NOT NULL,
	"description" text,
	"isCompleted" boolean DEFAULT false,
	"priority" varchar(10) DEFAULT 'medium',
	"dueDate" timestamp with time zone,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "focustimer_user_achievement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_user_achievement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"achievementId" integer NOT NULL,
	"unlockedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "focustimer_user_stats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focustimer_user_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"level" integer DEFAULT 1,
	"totalXp" integer DEFAULT 0,
	"currentStreak" integer DEFAULT 0,
	"longestStreak" integer DEFAULT 0,
	"totalFocusTime" integer DEFAULT 0,
	"totalSessions" integer DEFAULT 0,
	"lastActiveDate" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "focustimer_user_stats_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "focustimer_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "focustimer_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "focustimer_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "focustimer_account" ADD CONSTRAINT "focustimer_account_userId_focustimer_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_focus_session" ADD CONSTRAINT "focustimer_focus_session_userId_focustimer_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_focus_session" ADD CONSTRAINT "focustimer_focus_session_categoryId_focustimer_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."focustimer_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_post" ADD CONSTRAINT "focustimer_post_createdById_focustimer_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_session" ADD CONSTRAINT "focustimer_session_userId_focustimer_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_todo" ADD CONSTRAINT "focustimer_todo_userId_focustimer_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_todo" ADD CONSTRAINT "focustimer_todo_categoryId_focustimer_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."focustimer_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_user_achievement" ADD CONSTRAINT "focustimer_user_achievement_userId_focustimer_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_user_achievement" ADD CONSTRAINT "focustimer_user_achievement_achievementId_focustimer_achievement_id_fk" FOREIGN KEY ("achievementId") REFERENCES "public"."focustimer_achievement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focustimer_user_stats" ADD CONSTRAINT "focustimer_user_stats_userId_focustimer_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."focustimer_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "focustimer_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_user_idx" ON "focustimer_focus_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_date_idx" ON "focustimer_focus_session" USING btree ("startedAt");--> statement-breakpoint
CREATE INDEX "session_status_idx" ON "focustimer_focus_session" USING btree ("status");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "focustimer_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "focustimer_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "focustimer_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "todo_user_idx" ON "focustimer_todo" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "todo_category_idx" ON "focustimer_todo" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "todo_completed_idx" ON "focustimer_todo" USING btree ("isCompleted");--> statement-breakpoint
CREATE INDEX "user_achievement_user_idx" ON "focustimer_user_achievement" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_achievement_achievement_idx" ON "focustimer_user_achievement" USING btree ("achievementId");--> statement-breakpoint
CREATE INDEX "stats_user_idx" ON "focustimer_user_stats" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "stats_level_idx" ON "focustimer_user_stats" USING btree ("level");--> statement-breakpoint
CREATE INDEX "stats_xp_idx" ON "focustimer_user_stats" USING btree ("totalXp");