import { db } from "./index";
import { categories, achievements } from "./schema";

export async function seedDatabase() {
  try {
    // Insert default categories
    await db.insert(categories).values([
      {
        name: "Study",
        color: "#3B82F6",
        icon: "📚",
        isDefault: true,
      },
      {
        name: "Work",
        color: "#10B981",
        icon: "💼",
        isDefault: true,
      },
      {
        name: "Reading",
        color: "#8B5CF6",
        icon: "📖",
        isDefault: true,
      },
      {
        name: "Writing",
        color: "#F59E0B",
        icon: "✍️",
        isDefault: true,
      },
      {
        name: "Coding",
        color: "#EF4444",
        icon: "💻",
        isDefault: true,
      },
      {
        name: "Exercise",
        color: "#06B6D4",
        icon: "🏋️",
        isDefault: true,
      },
    ]).onConflictDoNothing();

    // Insert achievements
    await db.insert(achievements).values([
      // ⏱️ Session-Based Achievements
      {
        name: "First Strike",
        description: "Complete your first focus session",
        icon: "🎯",
        badgeColor: "#10B981",
        requirement: 1,
        type: "sessions",
        xpReward: 100,
      },
      {
        name: "Daily Driver",
        description: "Complete 5 sessions in a single day",
        icon: "🔄",
        badgeColor: "#3B82F6",
        requirement: 5,
        type: "daily_sessions",
        xpReward: 300,
      },
      {
        name: "Weekly Warrior",
        description: "Complete at least 1 session for 7 consecutive days",
        icon: "📅",
        badgeColor: "#8B5CF6",
        requirement: 7,
        type: "consecutive_days",
        xpReward: 500,
      },
      {
        name: "Back-to-Back",
        description: "Complete 3 sessions without a break",
        icon: "💼",
        badgeColor: "#F59E0B",
        requirement: 3,
        type: "consecutive_sessions",
        xpReward: 250,
      },
      {
        name: "Deep Dive",
        description: "Finish a single 90-minute session",
        icon: "🔥",
        badgeColor: "#EF4444",
        requirement: 90,
        type: "single_session_duration",
        xpReward: 400,
      },
      {
        name: "Momentum Flow",
        description: "Complete 10 sessions in one week",
        icon: "🌊",
        badgeColor: "#06B6D4",
        requirement: 10,
        type: "weekly_sessions",
        xpReward: 600,
      },
      {
        name: "Productivity Beast",
        description: "Complete 100 total sessions",
        icon: "🧠",
        badgeColor: "#F59E0B",
        requirement: 100,
        type: "sessions",
        xpReward: 1000,
      },

      // ⌛ Time Spent Achievements
      {
        name: "The First Hour",
        description: "Accumulate 60 minutes of focus time",
        icon: "⌚",
        badgeColor: "#10B981",
        requirement: 60,
        type: "total_time",
        xpReward: 150,
      },
      {
        name: "Time Collector",
        description: "Accumulate 10 hours total",
        icon: "⌛",
        badgeColor: "#3B82F6",
        requirement: 600,
        type: "total_time",
        xpReward: 500,
      },
      {
        name: "Master of Time",
        description: "Accumulate 50 hours total",
        icon: "🕰️",
        badgeColor: "#8B5CF6",
        requirement: 3000,
        type: "total_time",
        xpReward: 2000,
      },
      {
        name: "Slow and Steady",
        description: "Focus at least 20 minutes every day for 7 days",
        icon: "🐢",
        badgeColor: "#10B981",
        requirement: 7,
        type: "daily_minimum_time",
        xpReward: 400,
      },
      {
        name: "Time Titan",
        description: "4+ hours of focus in one day",
        icon: "💪",
        badgeColor: "#EF4444",
        requirement: 240,
        type: "daily_focus_time",
        xpReward: 800,
      },

      // 🔥 Streak Achievements
      {
        name: "Day One",
        description: "Start your first daily streak",
        icon: "🌱",
        badgeColor: "#10B981",
        requirement: 1,
        type: "streak",
        xpReward: 50,
      },
      {
        name: "Streaking!",
        description: "Maintain a 3-day streak",
        icon: "🔥",
        badgeColor: "#EF4444",
        requirement: 3,
        type: "streak",
        xpReward: 200,
      },
      {
        name: "Unstoppable",
        description: "Maintain a 7-day streak",
        icon: "⚡",
        badgeColor: "#F59E0B",
        requirement: 7,
        type: "streak",
        xpReward: 500,
      },
      {
        name: "Flow State",
        description: "Maintain a 14-day streak",
        icon: "🧬",
        badgeColor: "#8B5CF6",
        requirement: 14,
        type: "streak",
        xpReward: 1000,
      },
      {
        name: "Legendary",
        description: "30-day streak of daily focus",
        icon: "🏆",
        badgeColor: "#F59E0B",
        requirement: 30,
        type: "streak",
        xpReward: 2500,
      },

      // 🧩 Consistency & Discipline Achievements
      {
        name: "Everyday Hero",
        description: "Focus every day for 1 week",
        icon: "🗓️",
        badgeColor: "#10B981",
        requirement: 7,
        type: "consecutive_days",
        xpReward: 400,
      },
      {
        name: "Routine Riser",
        description: "Focus during the same hour each day for 5 days",
        icon: "📈",
        badgeColor: "#3B82F6",
        requirement: 5,
        type: "same_hour_consistency",
        xpReward: 350,
      },
      {
        name: "Early Bird",
        description: "Complete a session before 9 AM for 3 consecutive days",
        icon: "🌄",
        badgeColor: "#F59E0B",
        requirement: 3,
        type: "early_morning_sessions",
        xpReward: 300,
      },
      {
        name: "Night Owl",
        description: "Complete a session after 10 PM for 3 consecutive days",
        icon: "🌙",
        badgeColor: "#8B5CF6",
        requirement: 3,
        type: "late_night_sessions",
        xpReward: 300,
      },
      {
        name: "Distraction Slayer",
        description: "Complete a full session without pausing",
        icon: "🚫",
        badgeColor: "#EF4444",
        requirement: 1,
        type: "uninterrupted_session",
        xpReward: 200,
      },

      // 🎨 Fun / Meta Achievements
      {
        name: "Baby Steps",
        description: "Use the app two days in a row",
        icon: "👶",
        badgeColor: "#10B981",
        requirement: 2,
        type: "app_usage_streak",
        xpReward: 100,
      },
      {
        name: "Lurker",
        description: "Open the app 5 times without starting a session 😅",
        icon: "👁️",
        badgeColor: "#6B7280",
        requirement: 5,
        type: "app_opens_no_session",
        xpReward: 50,
      },
      {
        name: "Level Up!",
        description: "Reach level 5",
        icon: "🚀",
        badgeColor: "#8B5CF6",
        requirement: 5,
        type: "user_level",
        xpReward: 500,
      },
      {
        name: "Explorer",
        description: "Try all timer modes (Pomodoro, Custom, Break)",
        icon: "🧭",
        badgeColor: "#06B6D4",
        requirement: 3,
        type: "timer_modes_used",
        xpReward: 300,
      },
      {
        name: "Tag Master",
        description: "Create and focus using 5 different task tags",
        icon: "💡",
        badgeColor: "#F59E0B",
        requirement: 5,
        type: "unique_tags_used",
        xpReward: 400,
      },

      // Legacy achievements (keeping existing ones for backward compatibility)
      {
        name: "Focus Rookie",
        description: "Complete 5 focus sessions",
        icon: "🌱",
        badgeColor: "#10B981",
        requirement: 5,
        type: "sessions",
        xpReward: 200,
      },
      {
        name: "Focus Warrior",
        description: "Complete 25 focus sessions",
        icon: "⚔️",
        badgeColor: "#3B82F6",
        requirement: 25,
        type: "sessions",
        xpReward: 500,
      },
      {
        name: "Focus Master",
        description: "Complete 100 focus sessions",
        icon: "🏆",
        badgeColor: "#F59E0B",
        requirement: 100,
        type: "sessions",
        xpReward: 1000,
      },
      {
        name: "Getting Started",
        description: "Maintain a 3-day focus streak",
        icon: "🔥",
        badgeColor: "#EF4444",
        requirement: 3,
        type: "streak",
        xpReward: 300,
      },
      {
        name: "On Fire",
        description: "Maintain a 7-day focus streak",
        icon: "🚀",
        badgeColor: "#EF4444",
        requirement: 7,
        type: "streak",
        xpReward: 500,
      },
      {
        name: "Unstoppable",
        description: "Maintain a 30-day focus streak",
        icon: "💎",
        badgeColor: "#8B5CF6",
        requirement: 30,
        type: "streak",
        xpReward: 2000,
      },
      
      // Total time achievements
      {
        name: "Hour Hero",
        description: "Focus for 60 minutes total",
        icon: "⏰",
        badgeColor: "#06B6D4",
        requirement: 60,
        type: "total_time",
        xpReward: 150,
      },
      {
        name: "Time Titan",
        description: "Focus for 10 hours total",
        icon: "⚡",
        badgeColor: "#06B6D4",
        requirement: 600,
        type: "total_time",
        xpReward: 800,
      },
      {
        name: "Focus Legend",
        description: "Focus for 100 hours total",
        icon: "👑",
        badgeColor: "#F59E0B",
        requirement: 6000,
        type: "total_time",
        xpReward: 5000,
      },
    ]).onConflictDoNothing();

    console.log("Database seeded successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
} 